---
title: "Whittier Narrows WRP Analysis"
author: "Taylor Medina"
date: "12/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(janitor)
library(kableExtra)
```

**Concentration Difference:** $\Delta$ [PFA] = Effluent - Influent

- A positive concentration difference means that there is a greater concentration in the effluent than the influent

```{r}
whittier <- read_csv("sangabriel.csv") %>% 
  clean_names() %>% 
  filter(field_pt_name %in% c("WN_DCL_TER", "WN_RAW"), #WN_DCL_TER is the effluent and WN_RAW is the influent
         units == "NG/L",
         parvq == "=") %>% 
  unite("parameter", parameter:parameter_name, sep = " ")
```

```{r}
whittier_summary <- whittier %>% 
  group_by(parameter, field_pt_name, samp_date) %>% 
  summarize(mean_conc = mean(value, na.rm = TRUE)) %>% 
  pivot_wider(names_from = field_pt_name,
              values_from = mean_conc)

whittier_summary[is.na(whittier_summary)] <- 0

whittier_1 <- whittier_summary %>% 
  filter(samp_date == "11/19/2020") %>%
  mutate(difference = WN_DCL_TER - WN_RAW) %>% 
  filter(difference > 2)

whittier_2 <- whittier_summary %>% 
  filter(samp_date == "2/9/2021") %>%
  mutate(difference = WN_DCL_TER - WN_RAW) %>% 
  filter(difference > 2)

whittier_3 <- whittier_summary %>% 
  filter(samp_date == "5/25/2021") %>%
  mutate(difference = WN_DCL_TER - WN_RAW) %>% 
  filter(difference > 2)

whittier_4 <- whittier_summary %>% 
  filter(samp_date == "8/3/2021") %>%
  mutate(difference = WN_DCL_TER - WN_RAW) %>% 
  filter(difference > 2)
```

### Significant PFA concentration differences
```{r}
ggplot(data = whittier_1,
       aes(x = parameter, y = difference)) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_hline(yintercept = 0) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
  labs(x = "PFA",
       y = "Concentration difference (ng/L)",
       title = "11/19/2020") +
  theme_classic()

ggplot(data = whittier_2,
       aes(x = parameter, y = difference)) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_hline(yintercept = 0) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
  labs(x = "PFA",
       y = "Concentration difference (ng/L)",
       title = "2/9/2021") +
  theme_classic()

ggplot(data = whittier_3,
       aes(x = parameter, y = difference)) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_hline(yintercept = 0) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
  labs(x = "PFA",
       y = "Concentration difference (ng/L)",
       title = "5/25/2021") +
  theme_classic()

ggplot(data = whittier_4,
       aes(x = parameter, y = difference)) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_hline(yintercept = 0) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
  labs(x = "PFA",
       y = "Concentration difference (ng/L)",
       title = "8/3/2021") +
  theme_classic()
```

### Concentration difference summary table
```{r}
total_whittier <- rbind(whittier_1, whittier_2, whittier_3, whittier_4) %>% 
  select(parameter, samp_date, difference) %>% 
  pivot_wider(names_from = parameter,
              values_from = difference)

total_whittier %>% 
  kable() %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))
```

**Data:** Cantu, Esther (2021). WHITTIER NARROWS WATER RECLAMATION PLANT (WDR100001741). Retrieved from: https://geotracker.waterboards.ca.gov/profile_report?global_id=WDR100001741


